export const PASSWORD_MINIMUM_LENGTH = 8
export const PASSWORD_MAXIMUM_LENGTH = 20
export const USERNAME_MINIMUM_LENGTH = 4
export const USERNAME_MAXIMUM_LENGTH = 32
export const EMAIL_MAXIMUM_LENGTH = 32


